# Generated by Django 2.2.13 on 2020-06-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibroDiario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientolibro',
            name='tipo_de_movimiento',
        ),
        migrations.AddField(
            model_name='movimientolibro',
            name='egreso',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TipoDeMoviento',
        ),
    ]
