# Generated by Django 2.2.13 on 2020-06-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibroDiario', '0003_producto_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movimientolibro',
            name='medio_de_pago',
            field=models.ForeignKey(default='mercado pago', on_delete=django.db.models.deletion.DO_NOTHING, to='LibroDiario.MedioDePago'),
            preserve_default=False,
        ),
    ]
